# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7337b6e8a382d03dfbaab47c80853a1efe9da7ba20e647fc6d4a4b3b1220e8cf67da1c3c1937593cd2787a25a3933f9a8d9e43448ce33ff07f0b45fc786b8f5a

test:
  secret_key_base: 002ae0cdb28b8c6824fff76bcd407c9162fb93aa1f71c0c1a455f43bebcf391c6df659db02bc25672e4920bd5aea08eb7867a56a60bd5ea24728c7f1519901b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
